Don't try to build d8 from profiler tick processor scripts.
As described in the issue 1532, this may lead to building a 32-bit version over
existing x64-bit. It's better delegate to delegate this task to an user.

R=vitalyr@chromium.org
BUG=1532

Review URL: http://codereview.chromium.org/7309012

git-svn-id: http://v8.googlecode.com/svn/branches/bleeding_edge@8530 ce2b1a6d-e550-0410-aec6-3dcde31c8c00

diff --git a/tools/linux-tick-processor b/tools/linux-tick-processor
--- a/tools/linux-tick-processor
+++ b/tools/linux-tick-processor
@@ -8,12 +8,10 @@ fi
 [ "$D8_PATH" ] || D8_PATH=$tools_path/..
 d8_exec=$D8_PATH/d8
 
-if [ "$1" = "--no-build" ]; then
-  shift
-else
-# compile d8 if it doesn't exist, assuming this script
-# resides in the repository.
-  [ -x $d8_exec ] || scons -j4 -C $D8_PATH -Y $tools_path/.. d8
+if [ ! -x $d8_exec ]; then
+  echo "d8 shell not found in $D8_PATH"
+  echo "To build, execute 'scons <flags> d8' from the V8 directory"
+  exit 1
 fi
 
 
